### PR TITLE
Crown Support

### PR DESCRIPTION
**Pull request by Extrememist**
Addition of CRW(Crown) https://crown.tech/ 

Bitcore/Insight Explorer URLS (https://crw-bitcore.crown.tech/ https://crw2-bitcore.crown.tech/)

### CODE REVIEW

**Comment by prusnak** [comment]
https://crw-bitcore.crown.tech does not work

**Comment by Extrememist** [comment]
Currently use  https://crw2-bitcore.crown.tech/ they're currently not on latest chain but will be

**Comment by prusnak** [comment]
I will merge this once your services are stable enough.

**Comment by prusnak** [comment]
I am reworking the definitions and splitting the file `coins.json` into multiple smaller json files. These will reside in `defs/coins`, see https://github.com/trezor/trezor-common/commit/4fff5fbb7f3b184677e93e6cce320774835dc888

Your coin from this pull request was added in the commit above. Thanks!

**Pull request closed without merging**
