### PR TITLE
Add Zerocoin to coins.json

### PR DESCRIPTION
**Pull request by Technoprenerd**
Pull request to add Zerocoin (Zcoin), https://zcoin.io/, to Trezor.

The Bitcore Insight server is hosted, on https://insight.zcoin.io

This will ensure to integrate smoothly with the Trezor hardware wallet.
Double checked the parameters of Zcoin, hope all of them are correct.

Any other files I need to edit in order to get Zcoin in the Trezor wallet?

### CODE REVIEW

**Comment by prusnak** [comment]
The Insight server needs to be running HTTPS because HTTP will be blocked by a browser when accessing from HTTPS domain.

**Comment by Technoprenerd** [comment]
@prusnak : Did not know that, will configure HTTPS for that server through LetsEncrypt SSL's cert.
Will come back to you when that is configured.

**Comment by Technoprenerd** [comment]
@prusnak : Got Insight working on HTTPS (https://zcoinexplorer.technoprenerd.com/insight/).

**Comment by Technoprenerd** [comment]
Still some errors in the insight UI, Unparsed address [0] and value error (U) though.

**Comment by Technoprenerd** [comment]
The Bitcore Insight Server has this error: https://github.com/bitpay/bitcoin/issues/17 and https://github.com/bitpay/insight/issues/719. 

Have requested the Zcoin dev team to get this working in Zcoin source code.

**Comment by Technoprenerd** [comment]
The Bitcore Insight server is running: http://104.238.167.123/insight/

**Comment by yura-pakhuchiy** [comment]
"address_type" and "signed_message_header" are wrong in this PR. I created new PR with correct values https://github.com/trezor/python-trezor/pull/219

**Comment by yura-pakhuchiy** [comment]
"address_type" and "signed_message_header" are wrong in this PR. I created new PR with correct values https://github.com/trezor/trezor-common/pull/82

**Pull request closed without merging**
