### PR TITLE
Change stellar fields from int64 -> sint64

### PR DESCRIPTION
**Pull request by alepop**
Based on https://github.com/trezor/trezor-common/pull/63#issuecomment-380623804

### CODE REVIEW

**Comment by zulucrypto** [comment]
Thanks, looks good to me!

**Comment by prusnak** [comment]
@tsusanka ack?

**Comment by tsusanka** [comment]
LGTM, good to merge, cc @matejcik

**Comment by matejcik** [comment]
ack from me, now we just need https://github.com/trezor/python-trezor/pull/250

**Comment by prusnak** [comment]
:+1:

**Pull request merged**
