### PR TITLE
Add Denarius (DNR)

### PR DESCRIPTION
**Pull request by carsenk**
Added Denarius (DNR) support...let me know if anything else is needed!

This adds support for Denarius (DNR)
https://denarius.io
https://denarius.host
https://denariustalk.org
http://github.com/carsenk/denarius

### CODE REVIEW

**Comment by vertfox** [comment]
awesome!

**Comment by radar24** [comment]
I want denarius wallet on trezor so bad!!

**Comment by carsenk** [comment]
@prusnak Can we get a review on this? Been sitting here for a month...

**Comment by prusnak** [comment]
I don't see any backend URLs in your commit. What other Denarius client can be used with TREZOR?

**Comment by carsenk** [comment]
Denarius supports SPV, and BIP39. Below is the IPs of our servers. I would assume this is what you are looking for?

Our Electrumx Servers:
144.202.95.223
45.77.137.111
(Port 50001/50002)

**Comment by prusnak** [comment]
I am reworking the definitions and splitting the file `coins.json` into multiple smaller json files. These will reside in `defs/coins`, see https://github.com/trezor/trezor-common/commit/8a40c5f9ed73a6b07fe47d2db3e041872d544bfb

Your coin from this pull request was added in the commit above. Thanks!

**Pull request closed without merging**
