### PR TITLE
Added DigiPulse project to whitelist.

### PR DESCRIPTION
**Pull request by diidiiman**
Digipulse will improve users security and UX simplicity by utilising toolset available from integrations with Trezor.

### CODE REVIEW

**Comment by prusnak** [comment]
You should use TREZOR Connect for integrations with TREZOR: https://github.com/trezor/connect 

Whitelist will be obsoleted soon and using it is discouraged for new projects.

**Comment by diidiiman** [comment]
Ah snap. We were really looking forward on creating a simplified integration (just like pass manager extension).
Ok, thanks for the heads up!

**Comment by prusnak** [comment]
TBH integration using Connect is even easier, as it moves low-level application logic (such as PIN entering) to a separate environment and you don't have to deal with that.

**Comment by diidiiman** [comment]
It is easier for the devs, but more difficult for the end user, since the window block, different visual env. etc. This is why we wanted to go this path instead of the simplified solution so the UX would not suffer.
But I guess with connect we are limited to the popup window, right?

**Comment by prusnak** [comment]
There is a new version of Connect (v5) in progress, which can be used as React component, etc. so you won't be limited to popup window only.

**Comment by diidiiman** [comment]
Ok, thanks for the heads up!

**Pull request closed without merging**
