### PR TITLE
Add Groestlcoin (GRS) support

### PR DESCRIPTION
**Pull request by yura-pakhuchiy**
This PR depends on https://github.com/trezor/trezor-crypto/pull/148

### CODE REVIEW

**Comment by gruve-p** [comment]
Tested on emulator with Electrum-GRS (https://github.com/Groestlcoin/electrum-grs/tree/merge-3-1-2)
Works like a charm! Ack

**Comment by Yokomoko** [comment]
ACK. Reviewed and tested against electrum-grs 3.1.2

**Comment by duudl3** [comment]
Working well on Electrum-GRS (3.1.2). Ack

**Comment by Cold-A-Muse** [comment]
ACK, tested with electrum-grs 3.1.2 and seems to be working fine

**Comment by joenilan** [comment]
ACK tested. Seems good to me.

**Comment by HAMMERjah** [comment]
ACK

**Comment by gruve-p** [comment]
Ready for review @prusnak 
Bech-32 prefix has been added to https://github.com/satoshilabs/slips/blob/master/slip-0173.md
Electrum-GRS 3.1.2 https://github.com/Groestlcoin/electrum-grs/ has been merged to master wit Trezor support

Is this ready to get merged or does it need changes?

**Comment by prusnak** [comment]
I am reworking the definitions and splitting the file `coins.json` into multiple smaller json files. These will reside in `defs/coins`, see https://github.com/trezor/trezor-common/commit/8a40c5f9ed73a6b07fe47d2db3e041872d544bfb

Your coin from this pull request was added in the commit above. Thanks!

**Comment by gruve-p** [comment]
Thanks @prusnak 
Btw this PR depends on trezor/trezor-crypto#148

**Pull request closed without merging**
