### PR TITLE
Fix build with python 3.6

### PR DESCRIPTION
**Pull request by ehaupt**
Fix build with python 3.6

### CODE REVIEW

**Comment by prusnak** [comment]
What does `import locale ; locale.getpreferredencoding()` return? What OS are you on?

**Comment by ehaupt** [comment]
```console
# python3.6
Python 3.6.7 (default, Dec  4 2018, 01:10:52) 
[GCC 4.2.1 Compatible FreeBSD Clang 6.0.0 (tags/RELEASE_600/final 326565)] on freebsd11
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.getpreferredencoding()
'UTF-8'
```

**Comment by matejcik** [comment]
I'm inclined to say that non-UTF locales are unsupported.

I mean, we *could* explicitly specify encoding everywhere and it's a technically correct solution. OTOH, all our tooling is based on Click, which very explicitly [does not support ASCII locales](https://click.palletsprojects.com/en/7.x/python3/), so it's somewhat pointless.
So explicit encoding would only support other non-UTF locales (iso8859-*? shift-jis?) which are rather rare these days and personally I'm okay with declaring them unsupported.

What do you think @prusnak?

**Comment by prusnak** [comment]
I am fine with declaring non-UTF-8 locales as unsupported.

**Comment by matejcik** [comment]
alright, closing

**Pull request closed without merging**
