### PR TITLE
proto: add `auto_lock_delay_ms` field to ApplySettings and Features

### PR DESCRIPTION
**Pull request by romanz**
Following https://github.com/trezor/trezor-core/issues/163 (I am planning to add [this feature](https://github.com/romanz/trezor-mcu/tree/auto-lock) to TREZOR One).

### CODE REVIEW

**Comment by prusnak** [comment]
I am not sure whether we need to report the value in features.  Is there
any usecase when host needs to know the value?

**Comment by romanz** [comment]
I have added it there mainly due to similarity to other settings (e.g. label and language), but it's not required for this feature.
Should I just remove it?

**Comment by prusnak** [comment]
Yes. I would remove it. While label and language are required to be known by the host, this flag isn't.

Please add it to storage.proto, though. We don't use this file internally, but it's nice to keep track of stuff being stored in the storage.

**Comment by romanz** [comment]
Sounds good :)
Updated `trezor-common`, `trezor-mcu` and `python-trezor` PRs.

**Comment by saleemrashid** [comment]
Regarding returning the value in `Features`, isn't that useful for displaying the current value to the user? (i.e. in the Device Settings page)

**Comment by romanz** [comment]
@prusnak I'm fine with both suggestions, please let me know what do you prefer :)

**Comment by prusnak** [comment]
Let's not return that in Features for now. Thanks, Roman!

**Pull request merged**
