### PR TITLE
Pesetacoin

### PR DESCRIPTION
**Pull request by FundacionPesetacoin**

### CODE REVIEW

**Comment by prusnak** [comment]
You are missing `bip115` field from the json.

Icon size has to be 96x96 pixels

**Comment by FundacionPesetacoin** [comment]
Fixed!

**Comment by prusnak** [comment]
Backend URL cannot end with `/`, see this error https://travis-ci.org/trezor/trezor-common/builds/397978689#L558

**Comment by FundacionPesetacoin** [comment]
Fixed!

**Pull request merged**
