### PR TITLE
Update support for existing coin (NIX)

### PR DESCRIPTION
**Pull request by mattt21**
Re-add nix insight explorer, https://blockchain.nixplatform.io. 
Previously, the api used https://blockchain.nixplatform.io/nix-insight-api instead of the traditional **api**, this has been updated and should be responsive now.

Add NIX Wallet information to coin_details.json.

### CODE REVIEW

**Comment by matejcik** [comment]
coins_details is autogenerated, please move your wallets to `wallets.json`

**Comment by mattt21** [comment]
@matejcik Added in 227b22d.

**Comment by prusnak** [comment]
There are still conflicts in `defs/coins_details.json`

**Comment by mattt21** [comment]
@prusnak changes were removed.

**Comment by prusnak** [comment]
LGTM Thanks!

**Comment by mattt21** [comment]
One last thing @prusnak, how can we enable the t2 support as its current status for NIX is "soon".

**Comment by prusnak** [comment]
This will be changed automatically on the next firmware update (coming up in 2 weeks).

**Comment by mattt21** [comment]
Great, thanks!

**Pull request merged**
