### PR TITLE
Replace network with protocol magic on cardano

### PR DESCRIPTION
**Pull request by refi93**
See https://github.com/trezor/connect/pull/272 and https://github.com/trezor/trezor-core/pull/417

### CODE REVIEW

**Comment by refi93** [comment]
@prusnak thanks for pointing out, fixed

**Comment by prusnak** [comment]
@jpochyla @matejcik are  you OK with this change?

**Comment by matejcik** [comment]
there should be a corresponding PR to python-trezor, which is using the field
otherwise LGTM, except that I don't know how Cardano works so I trust @refi93 that this is correct from that angle :)

**Comment by refi93** [comment]
@matejcik there already is one: https://github.com/trezor/python-trezor/pull/342 I just need to fix the clicks emulation so the test does not hang. Will do probably tomorrow.

**Pull request merged**
