### PR TITLE
Tezos integration

### PR DESCRIPTION
**Pull request by jurajselep**

### CODE REVIEW

**Comment by prusnak** [comment]
Can you elaborate what `operation_bytes` contain? I am afraid we cannot let user sign any transaction without understanding these bytes and showing them on display.

**Comment by Adman** [comment]
@prusnak TezosSignTx is going to be refactored. `operation_bytes` should contain everything regarding transaction such as destination address, amount etc... Therefore we won't need other fields in that message.

**Comment by matejcik** [comment]
wouldn't it be better to do the opposite and decompose `operation_bytes`, similar to what NEM / Lisk / Stellar does?

**Comment by prusnak** [comment]
Please close all pull requests if you are going to change the code.
Also agreed with @matejcik. See how we handle messages for other
projects. Message should contain decomposed info so Trezor can show
info on the display.

**Comment by Adman** [comment]
After discussion with @matejcik I designed the messages in the following way: (xxxxx will be replaced by the exact type)

types.proto
```
/*
* Type of Tezos operation
* @used_in TezosSignTx
*/
enum TezosOperationType {
	Transaction = 8;
	Origination = 9;
	Delegation = 10;
}

/*
* Structure representing the common part for Tezos operations
* @used_in TezosSignTx
*/
message TezosOperationCommon {
	optional TezosOperationType tag = 1;
	optional bytes source = 2;
	optional xxxxx fee = 3;
	optional xxxxx counter = 4;
	optional xxxxx gas_limit = 5;
	optional xxxxx storage_limit = 6;
}

/*
* Structure representing additional information for transaction
* @used_in TezosSignTx
*/
message TezosTransactionType {
	optional xxxxx amount = 1;
	optional xxxxx destination = 2;
	optional xxxxx parameters = 3;
}

/*
* Structure representing additional information for origination
* @used_in TezosSignTx
*/
message TezosOriginationType {
	optional bytes manager_pubkey = 1;
	optional xxxxx balance = 2;
	optional bool spendable = 3;
	optional bool delegatable = 4;
	optional bytes delegate = 5;
	optional xxxxx script = 6;
}

/*
* Structure representing additional information for delegation
* @used_in TezosSignTx
*/
message TezosDelegationType {
	optional bytes delegate = 1;
}
```

messages.proto
```
message TezosSignTx {
	repeated uint32 address_n = 1;			// BIP-32 path to derive the key from master node
	optional TezosOperationCommon operation = 2;	// Tezos operation structure
	optional TezosTransactionType transaction = 3;	// Tezos transaction part
	optional TezosOriginationType origination = 4;	// Tezos origination part
	optional TezosDelegationType delegation = 5;	// Tezos delegation part
}
```

**Comment by Adman** [comment]
@prusnak Pushed. I need to firstly test it before merging, so when it's done, I'll ping you.

**Comment by prusnak** [comment]
Looks nice! Merging!

**Pull request merged**
