### PR TITLE
add eth network: ARTIS sigma1 & tau1

### PR DESCRIPTION
**Pull request by PeterTheOne**
Website: https://artis.eco
Block explorers: https://explorer.sigma1.artis.network/ http://explorer.tau1.artis.network/
slip0044: [246529](https://github.com/satoshilabs/slips/pull/495) (sigma1) & [246785](https://github.com/satoshilabs/slips/pull/495) (tau1)
chainIds: [246529](https://github.com/lab10-coop/sigma1/blob/1881ea80b475c10765d7a763ca6afd93df005b52/spec.json#L30) (sigma1) & [246785](https://github.com/lab10-coop/tau1/blob/master/spec.json#L30) (tau1)

Is the shortcut naming correct according to [Duplicate Detection](https://github.com/trezor/trezor-common/tree/master/defs#duplicate-detection)?

Depends on slip0044: https://github.com/satoshilabs/slips/pull/495

/cc @d10r

### CODE REVIEW

**Comment by matejcik** [comment]
No, the duplicate protection correctly catches this. Your shortcuts would be valid for ERC20 tokens, but the checks for non-tokens are stricter.

IIUC tau1 is your testnet? Not sure why you don't call it Artis Testnet but whatever ;)
In any case I'd recommend doing what other testnets are doing and calling the shortcut `tATS`

**Comment by PeterTheOne** [comment]
Thanks for your explanation. :) Changed to `ATS` and `tATS` now but we seem to have a duplicate with `erc20:eth:ATS (Authorship)`. So renaming to `ATS (ARTIS)` and `tATS (ARTIS)`, would help I guess?

**Comment by matejcik** [comment]
Alright, this should be OK on your side, but we'd have to update the Authorship token data as well, which is not easy to do.

For now, please run `python3 tools/support.py fix`, which will kick out the Authorship token and fix the checks. We will modify its data and readd it later.

**Comment by PeterTheOne** [comment]
Changed to `ATS (ARTIS sigma1)` and `tATS (ARTIS tau1)` but `python tools/support.py check --ignore-missing` now fails. :(

**Comment by PeterTheOne** [comment]
@matejcik Thanks for the info, Authorship is now removed..

**Comment by matejcik** [comment]
merged, thanks

**Comment by PeterTheOne** [comment]
thanks! :]

**Comment by prusnak** [comment]
I changed tATS slip44 entry to 1 (SLIP44 mandates testnet networks use 1 always).
I also changed shortcuts to be short (that's why they are called shortcuts, so they can fit on the display)

aeb6c35

**Comment by PeterTheOne** [comment]
Thanks for the merge, short shortcuts are much nicer now.

**Comment by PeterTheOne** [comment]
fyi MyCrypto integration is merged and released.

**Pull request merged**
