### PR TITLE
Add Unobtanium (UNO) Support

### PR DESCRIPTION
**Pull request by Flurbos**
Not sure the process on this but as far as im aware
i've done required changes ( And about to submit PR's)  for the following;
[trezor-common](https://github.com/flurbos/trezor-common "Unobtanium's Forked trezor-common")
[trezor-core](https://github.com/flurbos/trezor-core "Unobtanium's Forked trezor-core")
[trezor-wallet](https://github.com/flurbos/trezor-wallet "Unobtanium's Forked trezor-wallet")
[connect](https://github.com/flurbos/connect "Unobtanium's Forked connect")

If there's anything I've missed or another repo i need to fork please let me know, thanks in advanced!

Other info:
[Unobtanium chainparams.cpp](https://github.com/unobtanium-official/unobtanium/blob/master/src/chainparams.cpp "Unobtanium Information available here")
[Unobtanium website](https://unobtanium.uno "The Unoverse")

### CODE REVIEW

**Comment by prusnak** [comment]
Don't modify defs/coins_details.json

**Comment by matejcik** [comment]
none of the blockbook urls can be reached.

also i'm somewhat sure that we won't spin up a blockbook instance just because you say `uno1.trezor.io` in the json file. wtf? please fix this.

**Comment by Flurbos** [comment]
> none of the blockbook urls can be reached.
> 
> also i'm somewhat sure that we won't spin up a blockbook instance just because you say `uno1.trezor.io` in the json file. wtf? please fix this.

Was kind of unsure on direction so thought id pr and see how i go.
No offense intended, I have done most changes needed for blockbook but have not had a chance to finalize and run a server with.

Will fix asap.

**Comment by matejcik** [comment]
closing for now. If you wish to reopen, please wait until tomorrow and then submit a PR against https://github.com/trezor/trezor-firmware

**Pull request closed without merging**
