### PR TITLE
add blockbook URL for GameCredits

### PR DESCRIPTION
**Pull request by samadsajanlal**
Please see PR https://github.com/trezor/trezor-common/pull/213
Blockbook is now operating for GameCredits at the URL https://blockbook.gamecredits.network
The addition of GAME is still pending acceptance into the blockbook repo.

### CODE REVIEW

**Comment by samadsajanlal** [comment]
Blockbook's PR can be seen here: https://github.com/trezor/blockbook/pull/78

**Comment by samadsajanlal** [comment]
Hi prusnak,
Now that blockbook has accepted our PR, and this PR has been accepted into Trezor-common... is there any ETA for the firmware which will have GAME support?

Thanks - if this is not the right place to ask, please feel free to direct me to the correct place.

**Comment by prusnak** [comment]
Monday

**Comment by samadsajanlal** [comment]
Appreciate it and we look forward to the support!
The wallet that has Trezor integrated is https://electrum-game.org

**Pull request merged**
