### PR TITLE
Add NIX support

### PR DESCRIPTION
**Pull request by mattt21**
Would be great to have NIX integrated with the Trezor eco-system.

### CODE REVIEW

**Comment by matejcik** [comment]
please remove `coins_details.json` from the commit. the file will be regenerated by us.
(and NIX is definitely _not_ enabled on both Trezors at this moment anyway)

**Comment by mattt21** [comment]
@matejcik removed

**Comment by prusnak** [comment]
Please squash the commit into one

**Comment by mattt21** [comment]
Updated #245

**Pull request closed without merging**
