### PR TITLE
Prepare protocol for segwit.

### PR DESCRIPTION
**Pull request by jhoenicke**
These are the changes we need to support segwit.

### CODE REVIEW

**Comment by prusnak** [comment]
Thanks!

**Comment by ecdsa** [comment]
@jhoenicke can Trezor send to native segwit outputs? 
I get "RuntimeError: Failed to compile output" when trying with the latest firmware
(I set  txoutputtype.address to the bech32 serialized address, not sure if that is what trezor expects)

**Comment by saleemrashid** [comment]
@ecdsa Not at the moment https://github.com/trezor/trezor-mcu/blob/v1.5.2/firmware/transaction.c#L166

**Comment by prusnak** [comment]
Yes, native segwit is disabled in TREZOR for the time being.

**Comment by jhoenicke** [comment]
I have a branch with bech32 support, but it is not yet finished.  I plan to support it with PAYTOADDRESS. The address should be autodetected.

**Comment by ecdsa** [comment]
thank you for the clarification

**Pull request merged**
