### PR TITLE
coins: Added Bitcoin Private

### PR DESCRIPTION
**Pull request by csulmone**

### CODE REVIEW

**Comment by csulmone** [comment]
I followed the example of similar PRs on this project for adding new coins.

This change is accompanied with PR: https://github.com/trezor/python-trezor/pull/234

I have an electrum client that will accompany this release once merged, but would this be the repo to look at in order to integrate into the trezor webapp? https://github.com/satoshilabs/bitcore-deb

**Comment by jhoenicke** [comment]
Why `segwit: False`?  Does BTCP not support Segwit at all?  Does that mean that segwit addresses can't claim the coins?

**Comment by csulmone** [comment]
We added a way to claim segwit utxos without full segwit support, but full segwit support will be soft-forked in over the summer and I will submit a new pull request then.

**Comment by csulmone** [comment]
For consolidating BTCP from BTC inputs - I will be putting together a custom version of electrum that will be able to construct the correct transaction and submit it to the BTCP network.  We should be able to sign it  the usual way after that.

**Comment by csulmone** [comment]
Is there a canonical way to claim forked coins via trezor? I was thinking about creating a dedicated electrum front end that will display BTC->BTCP (standard and segwit) balances from the fork and support signing and broadcasting.

**Comment by csulmone** [comment]
We can work on messaging and a tutorial to make that as clear as possible. It should just be a matter of using an alternate bip44 coin type for the BTC based hardware wallet front end.

**Comment by prusnak** [comment]
Just don't try to reinvent the wheel and use the methods seen on older
already supported altcoins. The more new stuff you come up with, the
bigger is the chance I'll say no to merging the support.

**Comment by csulmone** [comment]
I agree Pavol - we want to use the least disruptive method possible.

**Comment by csulmone** [comment]
Would the next step for integration be a pull request into bitcore-deb?

**Comment by prusnak** [comment]
I am reworking the definitions and splitting the file `coins.json` into multiple smaller json files. These will reside in `defs/coins`, see https://github.com/trezor/trezor-common/commit/8a40c5f9ed73a6b07fe47d2db3e041872d544bfb

Your coin from this pull request was added in the commit above. Thanks!

**Comment by prusnak** [comment]
I am reworking the definitions and splitting the file `coins.json` into multiple smaller json files. These will reside in `defs/coins`, see https://github.com/trezor/trezor-common/commit/8a40c5f9ed73a6b07fe47d2db3e041872d544bfb

Your coin from this pull request was added in the commit above. Thanks!

**Comment by csulmone** [comment]
I am going to be putting together a new version of electrum-btcp that will understand how to spend BTC->BTCP segwit inputs as well as a guide on how to do it. Is this the last holdback to releasing BTCP in the next firmware update?

**Comment by csulmone** [comment]
We already have support for segwit BTC input spends on the full-node wallet.

**Comment by aramis1987** [comment]
Good job Sulmone !

**Pull request closed without merging**
